--
CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  college TEXT NOT NULL,
  department TEXT NOT NULL,
  year TEXT NOT NULL,
  events JSONB NOT NULL,
  -- Array of selected event objects
  total_fee NUMERIC NOT NULL,
  transaction_id TEXT,
  payment_status TEXT DEFAULT 'pending' -- pending, completed
);